<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1</name>
   <tag></tag>
   <elementGuidId>2f768f61-1035-4b06-a68b-705298513caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frameset > frameset > frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frameset/frameset/frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>2e13232a-409c-4c19-9d90-cc2e510266b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_2.html</value>
      <webElementGuid>632877e2-0b54-459e-8048-2c6d012db0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[1]</value>
      <webElementGuid>c047fde4-5ef7-4dfd-a508-76565046a273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame</value>
      <webElementGuid>5b070dff-979c-4818-8165-c7a8b0d67ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_2.html']</value>
      <webElementGuid>311f596f-b2ac-4cbe-b689-1a64b9441ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
