<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_1_2</name>
   <tag></tag>
   <elementGuidId>356884a5-5284-4468-a68c-87b9f45ea1e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frameset/frameset/frame[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>4cde01d3-8ac3-4e14-aa1d-4d699a6fbdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_3.html</value>
      <webElementGuid>545e977c-12f1-4e03-b01a-7f006ae6ab43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frameset[1]/frame[2]</value>
      <webElementGuid>0df782e0-df97-41f7-a359-801793ad0c3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frameset/frameset/frame[2]</value>
      <webElementGuid>5c3697eb-129c-49a3-bef5-1451692ca57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_3.html']</value>
      <webElementGuid>67ffb459-8d56-42a2-a091-cc0402560a08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
