<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame</name>
   <tag></tag>
   <elementGuidId>51b6797b-0dde-44bb-ad24-6052b55b7fe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>9ff9c5b8-8e4a-4286-9419-afe2fa2abc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>frame_1.html</value>
      <webElementGuid>81e18690-024e-4d27-a7de-7114265cf4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>aa6ca436-1920-403e-ba63-554c9afd7f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>ea219a04-a299-4c91-9752-046a6bb277b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'frame_1.html']</value>
      <webElementGuid>06a8953e-db30-4abc-a972-0d43a7e1028b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
